<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="Half_Rotation" Id="{6ea449ad-6b83-4493-8b59-1e2f14b2084d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Half_Rotation
VAR
	bRotation_Trig : BOOL;
	bFlip_Side: BOOL;
	bProcess: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Half_Rotation">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>